# Backend jobs
# Build, lint and test backend development environment for a site
build-back:
  parameters:
    site:
      type: string
  docker:
    - image: cimg/python:3.10.2
  working_directory: ~/nau/sites/<< parameters.site >>
  steps:
    - checkout:
        path: ~/nau
    - restore_cache:
        keys:
          - v1-back-dependencies-<< parameters.site >>-{{ .Revision }}
    - run:
        name: Install development dependencies
        command: >
          pip install \
            --user \
            -r requirements/base.txt \
            -r requirements/dev.txt
    - save_cache:
        paths:
          - ~/.local
        key: v1-back-dependencies-<< parameters.site >>-{{ .Revision }}

lint-back:
  parameters:
    site:
      type: string
  docker:
    - image: cimg/python:3.10.2
  working_directory: ~/nau/sites/<< parameters.site >>/src/backend/
  steps:
    - checkout:
        path: ~/nau
    - restore_cache:
        keys:
          - v1-back-dependencies-<< parameters.site >>-{{ .Revision }}
    - run:
        name: Lint code with flake8
        command: ~/.local/bin/flake8
    - run:
        name: Lint code with isort
        command: ~/.local/bin/isort --check-only .
    - run:
        name: Lint code with black
        command: ~/.local/bin/black .
    - run:
        name: Lint code with pylint
        command: ~/.local/bin/pylint .
    - run:
        name: Lint code with bandit
        command: ~/.local/bin/bandit -qr .
    - run:
        name: Lint code with raincoat
        command: ~/.local/bin/raincoat

test-back:
  parameters:
    site:
      type: string
  docker:
    - image: cimg/python:3.10.2
      environment:
        DB_ENGINE: django.db.backends.mysql
        DB_OPTION_CHARSET: utf8mb4
        DB_HOST: 127.0.0.1
        DB_NAME: richie
        DB_PASSWORD: pass
        DB_PORT: 3306
        DB_USER: richie_user
        DJANGO_CONFIGURATION: Test
        DJANGO_SECRET_KEY: ThisIsAnExampleKeyForTestPurposeOnly
        DJANGO_SETTINGS_MODULE: << parameters.site >>.settings
        PYTHONPATH: /home/circleci/nau/src/backend
    - image: circleci/mysql:8.0-ram
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: test_richie
        MYSQL_PASSWORD: pass
        MYSQL_USER: richie_user
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    - image: docker.io/bitnami/redis:6.0-debian-10
      environment:
        ALLOW_EMPTY_PASSWORD: "yes"
        REDIS_REPLICATION_MODE: master
      name: redis-primary
    - image: docker.io/bitnami/redis-sentinel:6.0-debian-10
      environment:
        REDIS_MASTER_HOST: redis-primary
      name: redis-sentinel
  working_directory: ~/nau/sites/<< parameters.site >>/src/backend
  steps:
    - checkout:
        path: ~/nau
    - restore_cache:
        keys:
          - v1-back-dependencies-<< parameters.site >>-{{ .Revision }}
    - run:
        name: Install gettext (required to compile messages)
        command: |
          sudo apt-get update
          sudo apt-get install -y gettext
    - run:
        name: Compile translations
        command: python manage.py compilemessages || true
    - run:
        name: Run tests
        command: |
            dockerize \
              -wait tcp://localhost:3306 \
              -timeout 60s \
                ~/.local/bin/pytest
